baseURL = "https://mate-desktop.github.io/mate-wiki-new/"
title = "MATEwiki"
theme = "hugo-geekdoc"

pluralizeListTitles = false

enableEmoji = true

# Geekdoc required configuration
pygmentsUseClasses = false #  Due to Geekdoc this should be true
pygmentsCodeFences = true
disablePathToLower = true

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    # unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "tango"
    tabWidth = 4

[params]
  # (Optional, default none) Set source repository location. Used for 'Edit this page' links.
  # You can also specify this parameter per page in front matter.
  geekdocRepo = "https://github.com/mate-desktop/mate-wiki-new"

  # (Optional, default none) Enable 'Edit this page' links. Requires 'GeekdocRepo' param
  # and path must point to 'content' directory of repo.
  # You can also specify this parameter per page in front matter.
  geekdocEditPath = "edit/master/content"

  # (Optional, default static/brand.svg) Set the path to a logo for the Geekdoc
  # relative to your 'static/' folder.
  geekdocLogo = "brand.png"

